# Wrangler configuration for Pages project
name = "mracad"
compatibility_date = "2023-10-30"

# Pages configuration - this is the only required field for Pages
pages_build_output_dir = ".next/standalone"

# Pages configuration
[placement]
mode = "smart"

# Increase resource limits to avoid timeouts
[limits]
cpu_ms = 50

[env.production]
name = "mracad-production"

[env.preview]
name = "mracad-preview"