# Wrangler configuration file for MIRA ACADEMY project
name = "mracad"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]
main = "workers-site/index.js"
pages_build_output_dir = ".next"

# Pages configuration
[placement]
mode = "smart"

# Increase resource limits to avoid timeouts
[limits]
cpu_ms = 50

[env.production]
name = "mracad-production"
route = "mracad.pages.dev/*"

[env.preview]
name = "mracad-preview" 