name: Deploy to Cloudflare Pages

on:
  push:
    branches: [master]
  workflow_dispatch:  # Allow manual triggering

# Add permissions for deployments
permissions:
  contents: read
  deployments: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set timeout to avoid hung builds
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Create GitHub deployment
      - name: Create GitHub deployment
        id: deployment
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          description: "Deploy to Cloudflare Pages"
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Next.js application
        run: npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          NEXT_TELEMETRY_DISABLED: 1
          
      - name: Verify build output
        run: |
          echo "Checking build output structure..."
          ls -la .next || echo ".next directory not found"
          ls -la .next/standalone || echo ".next/standalone directory not found"
          
      - name: Prepare standalone for deployment
        run: |
          echo "Preparing standalone directory for deployment..."
          # Create complete deployment structure
          mkdir -p .next/standalone/.next
          
          # Copy public directory (if exists)
          if [ -d "public" ]; then
            cp -r public .next/standalone/ || echo "No public directory to copy"
          fi
          
          # Ensure static directory is properly copied
          if [ -d ".next/static" ]; then
            mkdir -p .next/standalone/.next/static
            cp -r .next/static/* .next/standalone/.next/static/ || echo "No static files to copy"
          fi
          
          # Copy any server files that might be needed
          if [ -d ".next/server" ]; then
            mkdir -p .next/standalone/.next/server
            cp -r .next/server/* .next/standalone/.next/server/ || echo "No server files to copy"
          fi
          
          # Add the required file to make it deployable to Cloudflare Pages
          echo '{"version":1,"paths":{}}' > .next/standalone/_routes.json
          echo '/* /index.html 200' > .next/standalone/_redirects
          
          # Create a Cloudflare worker to handle routing
          cat > .next/standalone/_worker.js << 'EOF'
          export default {
            async fetch(request, env) {
              const url = new URL(request.url);
              // Handle static assets from .next directory
              if (url.pathname.startsWith('/.next/')) {
                // Strip leading slash
                const assetPath = url.pathname.slice(1);
                return env.ASSETS.fetch(new Request(new URL(assetPath, request.url), request));
              }
              // Handle root path
              if (url.pathname === '/') {
                return env.ASSETS.fetch(new Request(new URL('/index.html', request.url), request));
              }
              // Default handling
              return env.ASSETS.fetch(request);
            }
          };
          EOF
          
          # List the final structure for debugging
          echo "Final deployment structure:"
          find .next/standalone -type f | sort || echo "Failed to list files"
          
      - name: Deploy to Cloudflare Pages
        id: cloudflare-deploy
        run: |
          # Install wrangler globally
          npm install -g wrangler@latest
          # Deploy to Cloudflare Pages and capture output
          DEPLOYMENT_OUTPUT=$(wrangler pages deploy .next/standalone --project-name=mracad --branch=master --commit-dirty=true)
          echo "$DEPLOYMENT_OUTPUT"
          
          # Extract the deployment URL using grep and sed
          PREVIEW_URL=$(echo "$DEPLOYMENT_OUTPUT" | grep -o 'https://[a-zA-Z0-9.-]*.mracad.pages.dev' | head -1)
          if [ -z "$PREVIEW_URL" ]; then
            PREVIEW_URL="https://mracad.pages.dev"  # Default URL if not found
          fi
          
          # Set output variables for use in later steps
          echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
      # Update GitHub deployment status
      - name: Update deployment status
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "success"
          environment-url: ${{ steps.cloudflare-deploy.outputs.preview_url }}
          
      - name: Purge Cloudflare Cache
        if: success()
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}' 